### ISSUE TITLE
sender について説明

### ISSUE THREAD

**Issue by c-su** [meg-github/6-6slider#1]
sender について調べて報告してください．
14行目で使ってるやつです．

・sender の基本的なこと
・sender の利点

といったことについて調べてください．
400字〜600字ぐらいにまとめておきましょう．
参考にしたサイトなども掲載しておいてください．

**Comment by meg-github** [comment]
senderとは，Actionを送ってくる部品(送り手)そのものを引数として渡すことができるコマンド．L15を例にすると，UISlider（画面のスライドバー）そのものを引数として，Labelに表示することを行っている．Action接続でコードと接続した部品は，指定のアクションが起こった時のみ呼び出されるので，メソッド内で変更を加えるには，Outlet（プロパティ）接続を別に書き加える必要があるため，コードが冗長になる恐れがあるが，senderをメソッドに引数として渡し，その値に応じた命令を追加することで，Outletで接続することなく変更を加えることが可能になる（資料P177）．

今とりあえずこんな感じです．270字くらいです．もうすこし調べて書き加えます！

**Comment by c-su** [comment]
OKです！
