### ISSUE TITLE
最初から書かれてる関数の意味

### ISSUE THREAD

**Issue by c-su** [meg-github/6-6slider#2]
Xcode で新規プロジェクトを立ち上げると最初からいくつかの関数が書かれています．
例えば，ViewControllerに書かれてる．

・viewDidLoad
・didReceiveMemoryWarning

この２つの関数の意味はなんでしょうか？

**Comment by meg-github** [comment]
viewDidLoadは，プログラムが起動した時，画面が表示される直前に呼び出される関数．ここにはviewが画面上に呼び出された時点で実行したい処理を書いておく．
didReceiveMemoryWarningは，実行中にメモリを使いすぎた際に呼び出される関数．メモリ不足などを検知してクラッシュを防ぐために使われる．

こんな感じでしょうか？

**Comment by c-su** [comment]
OKです！
